Update installation.md
AdobeDocs/commerce-operations.en pull request #37
Opened 2022-09-20 17:54 UTC by null93

## Purpose of this pull request

Spelling and word choice. `grep` was repeated twice in list, assumed `egrep`. Also `Inpack` was written instead of `Unpack`.

## Affected pages

https://experienceleague.adobe.com/docs/commerce-operations/tools/site-wide-analysis-tool/installation.html

- ...

## Links to Magento Open Source code

- ...

2022-09-20 18:36 UTC, jeff-matthews commented
Thanks for the contribution @null93. Please complete the PR description.

2022-09-20 18:40 UTC, null93 commented
@jeff-matthews Done, apologies though commit would speak for itself. Let me know if there is anything else. Thanks!

2022-09-20 18:49 UTC, jeff-matthews commented
Thanks @null93! The description helps us prioritize and process contributions.

2022-09-30 15:57 UTC, almarchenko approved these changes

2022-10-03 15:17 UTC, yvoronoy requested changes

2022-10-03 15:17 UTC, yvoronoy commented on help/tools/site-wide-analysis-tool/installation.md
> +  - `egrep`
These dependencies must be installed "php" "wget" "awk" "nice" "grep" "openssl"

2022-11-07 21:32 UTC, null93 commented on help/tools/site-wide-analysis-tool/installation.md
> +  - `egrep`
Done, sorry for the delay. I was off for a month.

2022-11-07 22:18 UTC, yvoronoy approved these changes

2022-12-21 20:34 UTC, null93 commented
guess not

2022-12-21 20:34 UTC, closed without merging