Update to the UCT overview page
AdobeDocs/commerce-operations.en pull request #7
Opened 2022-02-18 13:03 UTC by sgonzalezmangana

## Purpose of this pull request

This pull request (PR) ...

## Affected pages

- ...

## Links to Magento Open Source code

- ...

2022-02-18 13:04 UTC, sgonzalezmangana commented
@sivaschenko @danidelcar I'm reviewing UCT documentation and updating the content that is not too technical. Please have a look to these minor changes

2022-02-18 14:01 UTC, jeff-matthews commented
@sgonzalezmangana, you'll need to sign the Adobe CLA before we can finish processing this contribution.

@sivaschenko, I sent you an invitation to join the AdobeDocs org so that we can assign you as a reviewer.

2022-02-18 14:05 UTC, danidelcar approved these changes
Approved, a couple of comments, thanks!

2022-02-18 14:05 UTC, danidelcar commented on help/upgrade/upgrade-compatibility-tool/overview.md
> +## Resources
Missing a couple of spaces in between title and lists:

```
## Resources

We have developed other resources to help you understand Adobe Commerce upgrades, these are links to key resources:

- [Upgrade guide](https://experienceleague.adobe.com/docs/commerce-operations/assets/adobe-commerce-2-4-upgrade-guide.pdf)
- [Upcoming releases](https://devdocs.magento.com/release/)
- [Community Resources](https://devdocs.magento.com/community/resources/resources.html) page for more information.

```

2022-02-18 14:05 UTC, danidelcar commented on help/upgrade/upgrade-compatibility-tool/overview.md
> +The Upgrade Compatibility Tool uses rules defined within our [Coding Standards](https://devdocs.magento.com/guides/v2.4/coding-standards/bk-coding-standards.html), to ensure your project is following
Don't forget to include the tag, so name is not translated nor localized: [!DNL Upgrade Compatibility Tool].
So:

```
The [!DNL Upgrade Compatibility Tool] uses rules defined within our [Coding Standards](https://devdocs.magento.com/guides/v2.4/coding-standards/bk-coding-standards.html), to ensure your project is following Adobe Commerce best practices, and at the same time allowing you to improve and extend the [!DNL Upgrade Compatibility Tool] compatibility analysis by contributing to this project.

Refer to the [Contribute](https://devdocs.magento.com/guides/v2.4/coding-standards/contributing.html)  topic for more information on contributing to this project.
```

2022-02-18 14:06 UTC, danidelcar commented
@sgonzalezmangana I'll address the changes of the PR

2022-02-18 14:08 UTC, jeff-matthews requested changes
The `[!DNL ]` syntax prevents the localization engine from localizing the term. See the [authoring guide ](https://experienceleague.adobe.com/docs/authoring-guide-exl/using/authoring/localization/localize.html?lang=en) for more info.

2022-02-18 14:08 UTC, jeff-matthews commented on help/upgrade/upgrade-compatibility-tool/overview.md
> +The Upgrade Compatibility Tool uses rules defined within our [Coding Standards](https://devdocs.magento.com/guides/v2.4/coding-standards/bk-coding-standards.html), to ensure your project is following
```suggestion
The [!DNL Compatibility Tool] uses rules defined within our [Coding Standards](https://devdocs.magento.com/guides/v2.4/coding-standards/bk-coding-standards.html) to ensure that your project is following Adobe Commerce best practices and to help you improve and extend the [!DNL Compatibility Tool]. Check the [Contributing](https://devdocs.magento.com/guides/v2.4/coding-standards/contributing.html) page for more information.
```

2022-02-18 14:08 UTC, jeff-matthews commented on help/upgrade/upgrade-compatibility-tool/overview.md
> +We have developed other resources to help you understand Adobe Commerce upgrades, these are links to key resources:
```suggestion

We have developed the following resources to help you understand Adobe Commerce upgrades:
```

2022-02-18 14:08 UTC, jeff-matthews commented on help/upgrade/upgrade-compatibility-tool/overview.md
> +- [Upgrade guide](https://experienceleague.adobe.com/docs/commerce-operations/assets/adobe-commerce-2-4-upgrade-guide.pdf)
```suggestion
- [Upgrade guide](https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/overview.html)
```

2022-02-18 14:19 UTC, danidelcar commented on help/upgrade/upgrade-compatibility-tool/overview.md
> +The Upgrade Compatibility Tool uses rules defined within our [Coding Standards](https://devdocs.magento.com/guides/v2.4/coding-standards/bk-coding-standards.html), to ensure your project is following
@jeff-matthews should be  [!DNL Upgrade Compatibility Tool] right?

2022-02-18 14:26 UTC, jeff-matthews commented on help/upgrade/upgrade-compatibility-tool/overview.md
> +The Upgrade Compatibility Tool uses rules defined within our [Coding Standards](https://devdocs.magento.com/guides/v2.4/coding-standards/bk-coding-standards.html), to ensure your project is following
@danidelcar, yes. My mistake. I'll edit my suggestion.

2022-02-18 14:27 UTC, jeff-matthews commented on help/upgrade/upgrade-compatibility-tool/overview.md
> +The Upgrade Compatibility Tool uses rules defined within our [Coding Standards](https://devdocs.magento.com/guides/v2.4/coding-standards/bk-coding-standards.html), to ensure your project is following
@danidelcar, suggestion updated.

2022-02-18 14:36 UTC, jeff-matthews approved these changes

2022-02-18 14:45 UTC, danidelcar approved these changes
good to go after signing Adobe CLA!

2022-02-18 18:18 UTC, jeff-matthews commented
@sgonzalezmangana, in the future, please complete the PR description.

2022-02-22 12:31 UTC, sgonzalezmangana commented
> 

@jeff-matthews how can I sign the Adobe CLA?

2022-02-22 12:36 UTC, danidelcar commented
> > 
> 
> @jeff-matthews how can I sign the Adobe CLA?

@jeff-matthews shared link to sign it with @sgonzalezmangana

2022-02-22 12:44 UTC, sgonzalezmangana commented
> > > 
> > 
> > 
> > @jeff-matthews how can I sign the Adobe CLA?
> 
> @jeff-matthews shared link to sign it with @sgonzalezmangana

Signed!

2022-02-22 12:49 UTC, sgonzalezmangana commented
Testing notifications @sgonzalezmangana

2022-02-22 14:53 UTC, merged